### ISSUE TITLE
Inputs (like touch sensor) as some sort of event stream

### ISSUE THREAD

**Issue by wischi-chr** [bricks-rs/nxt#2]
Thank you very much for sharing you work. I recently got my hand on a mindstorms nxt 2.0 robot and your library is really ergonomic and worked right out of the box.

I wrote a little demo application to remotely control the robot via bluetooth and it works great. After that I tried to use the touch sensors (nxt buttons) to control the robot and noticed that the only way to query them was via polling. Would it be possible to make an API could read the state (or actually state-transitions) without polling? For example with some soft of event stream or is that a limitation of the underlying nxt protocol.

How did you figure out the protocol? Is there some nxt 2.0 wiki or something?

**Comment by sciguy16** [comment]
It's been a while since I last worked on this, but I don't believe there's support for anything but polling. I used a combination of the [NXC firmware souce](https://sourceforge.net/p/mindboards/code/HEAD/tree/lms_nbcnxc/trunk/AT91SAM7S256/Source/c_cmd.c) and the [NXT Python](https://github.com/schodet/nxt-python) project.

From what I remember it's just a simple command/response protocol that's only initiated from the host side of the socket. If you need quick reactions to button presses then you'll probably need to run a program on the brick at the same time.

**Comment by wischi-chr** [comment]
Thank you for your answer and the links. If I find something I'll post an update here. I'm closing this issue for now.
